version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  publisher:
    build: ./publisher
    container_name: publisher
    depends_on:
      - mosquitto

  subscriber:
    build: ./subscriber
    container_name: subscriber
    depends_on:
      - mosquitto
